apiVersion: v1
kind: Service
metadata:
  name: trademarkroyalty-web
spec:
  selector:
    app: trademarkroyalty-web
  ports:
    - protocol: TCP
      port: 8084
      targetPort: 80
      nodePort: 30008
  type: NodePort